[tool.poetry]
name = "cryptoinsighto"
version = "0.1.0"
description = ""
authors = ["Than Htut Soe <than@consigli.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
